# Standard docker-compose file which defines all services that Gymboard uses in
# a deployment.
version: '3'

services:
  # Database for gymboard-api.
  api-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gymboard-api-dev
      POSTGRES_PASSWORD: testpass
  
  # Database for the gymboard-cdn.
  cdn-db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: gymboard-cdn-dev
      POSTGRES_PASSWORD: testpass

  mailhog:
    image: mailhog/mailhog
    restart: always
    expose:
      - "8025"
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
